"""añadir columna

Revision ID: 6ef14e7f4fb3
Revises: 
Create Date: 2023-02-23 23:52:20.663958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ef14e7f4fb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('category', sa.String(20)))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###
