"""cambiar columna

Revision ID: b14fc9856ce1
Revises: 6ef14e7f4fb3
Create Date: 2023-02-24 00:18:02.253721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b14fc9856ce1'
down_revision = '6ef14e7f4fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'Usuario', 'category',type_=sa.String(30), nullable=True, new_column_name='permisos'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###
